import "../public/styles/globals.css";

import { Inter } from "next/font/google";
import Head from "next/head";
import { ReactNode } from "react";

import { AuthProvider } from "@/providers/AuthProvider";
import TranslationProvider from "@/providers/TranslationProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Roulette app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className="h-full">
      <Head>
        <link rel="icon" href="/assets/images/favicon.ico" />
      </Head>
      <body className={`${inter.className} h-full flex flex-col`}>
        <AuthProvider>
          <TranslationProvider>
            <div className="grow">{children}</div>
          </TranslationProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
